@echo on

set MAVEN_MIRROR=https://repo1.maven.org/maven2
set POSTGRES_JDBC_VERSION=42.7.3
set POSTGRES_JDBC_JAR_NAME=postgresql

curl %MAVEN_MIRROR%/org/postgresql/%POSTGRES_JDBC_JAR_NAME%/%POSTGRES_JDBC_VERSION%/%POSTGRES_JDBC_JAR_NAME%-%POSTGRES_JDBC_VERSION%.jar ^
-o ./%POSTGRES_JDBC_JAR_NAME%-%POSTGRES_JDBC_VERSION%.jar

pause