#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER jira WITH PASSWORD 'jira';
CREATE SCHEMA AUTHORIZATION jira;
CREATE DATABASE jira;
GRANT ALL PRIVILEGES ON DATABASE jira TO jira;
ALTER DATABASE jira OWNER TO jira; 
EOSQL